export type {
  ServerActionRequest,
  ServerActionResponse,
  ServerIpCaptureRevertResponse,
  ServerGameEvent,
  ServerGameSnapshot,
  ServerIpActivitySnapshot,
  ServerIpModerationSnapshot,
  ServerIpTimeoutRequest,
  ServerIpTimeoutResponse,
  ServerSeasonResetEvent,
  ServerStatsSnapshot,
  ServerStateResponse,
  ServerWorldUpdateEvent,
} from "../../src/game/serverProtocol.ts"
